### ISSUE TITLE
Component: Badge

### ISSUE THREAD

**Issue by daniknewgarden** [daniknewgarden/exo-ui#24]
# Context:
- As a part of our base components milestone we want to create a `Badge` component.
- More info about badges (in the case with material design) - [docs link](https://m3.material.io/components/badges/overview).
# Design:
## Screenshots:
![Badges (2)](https://github.com/daniknewgarden/exo-ui/assets/38109617/897a8d45-abfe-431e-a3c4-0e437aef129a)
## Links:
[<img src="https://www.bynder.com/images/meta/meta-figma.jpg" width="100">](https://www.figma.com/file/704It4Imc2BSHeIM65asRD/EXO-KIT-by-Anthony-Choren?type=design&node-id=269%3A562&mode=design&t=J311Ioc1W0jDxcq7-1)
# Acceptance criteria:
- [ ] The new `Badge` component is created.
- [ ] It accepts the following props:
  - [ ] Icon.
  - [ ] Reverse.
- [ ] It is documented.
  - [ ] In storybook.
  - [ ] By writing unit tests.

**Comment by lulek1410** [comment]
@daniknewgarden  i think there is some kind of a problem with the type check that has been implemented. When i try to commit changes for this issue i get:

✖ Type checks failed.
file:///home/lulek1410/exo/.husky/scripts/types-check.js:27
    if (err.code === 2 && stdout) {
            ^

TypeError: Cannot read properties of null (reading 'code')
    at file:///home/lulek1410/exo/.husky/scripts/types-check.js:27:13
    at ChildProcess.exithandler (node:child_process:411:7)
    at ChildProcess.emit (node:events:512:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

Node.js v19.7.0
husky - pre-commit hook exited with code 1 (error)
git exited with error code 1

From what i checked it seems that the err object is null
