### ISSUE TITLE
Component: Avatar

### ISSUE THREAD

**Issue by daniknewgarden** [daniknewgarden/exo-ui#25]
# Design:
### With image:
Users can upload images. <br>
![Image](https://github.com/daniknewgarden/exo-ui/assets/38109617/5d820b8e-6609-4e38-bb2b-0c8f5303204a)
### With initials:
Otherwise by default the user's initials are displayed. <br>
![Default](https://github.com/daniknewgarden/exo-ui/assets/38109617/4878d822-1b82-491b-8403-1abfab3425ac)
### With status:
Avatars can show informations about the user like status. <br>
![Status](https://github.com/daniknewgarden/exo-ui/assets/38109617/fb8b9866-fd5c-451b-85ec-ce553debc076)
## Links:
[<img src="https://www.bynder.com/images/meta/meta-figma.jpg" width="100">](https://www.figma.com/file/704It4Imc2BSHeIM65asRD/EXO-KIT-by-Anthony-Choren?type=design&node-id=269%3A1155&mode=design&t=J311Ioc1W0jDxcq7-1)
# Acceptance criteria:
- [ ] The new `Avatar` component is created.
- [ ] It accepts the following props:
  - [ ] Image.
  - [ ] Name.
  - [ ] Status.
  - [ ] Size.
- [ ] It is documented.
  - [ ] In storybook.
  - [ ] By writing unit tests.

**Comment by test12kfk** [comment]
Hey, would you mid to assign this issue to me?

**Comment by lulek1410** [comment]
Hi, since im already set up for this project i could try to resolve this issue. I have two question though. In this Avatar component the size is sopesed to be freely customizable? I mean  can the user input any size they want or is it sopesed to be fixed like in the Button component. Also there seems to be some inconsistency with the provided figma project. The avatars with status have 2px border while others have none so which should it be?

**Comment by daniknewgarden** [comment]
> Hi, since im already set up for this project i could try to resolve this issue. I have two question though. In this Avatar component the size is sopesed to be freely customizable? I mean  can the user input any size they want or is it sopesed to be fixed like in the Button component. Also there seems to be some inconsistency with the provided figma project. The avatars with status have 2px border while others have none so which should it be?

Hey @lulek1410 ! Thank you for your support 🤗. 
Here are quick answers: 
1. The `size` prop should have only 5 values, it could be a scale from 1-5 or names like, extra large (details), large, medium, small, tiny. 
2. Yes, we have this inconsistency, so let's just ignore the border for now. 

Assigning the issue to you ✅.
