### ISSUE TITLE
Component: Link

### ISSUE THREAD

**Issue by daniknewgarden** [daniknewgarden/exo-ui#27]
# Context:
- We need a simple link component. 
# Design:
## Screenshots:
Special text links with the focused state. <br>
![Links](https://github.com/daniknewgarden/exo-ui/assets/38109617/6b2e6a2a-d636-4838-9ba9-46395f17d74e)
## Links:
[<img src="https://www.bynder.com/images/meta/meta-figma.jpg" width="100">](https://www.figma.com/file/704It4Imc2BSHeIM65asRD/EXO-KIT-by-Anthony-Choren?type=design&node-id=277%3A6&mode=design&t=P16zNbV5LlX63hlH-1)
# Acceptance criteria:
- [x] The new `Link` component is created.
- [x] It is documented.
  - [x] In storybook.
  - [x] By writing unit tests.

**Comment by lulek1410** [comment]
Hi, im new to open source contributions but this issue seems perfect to get started. Would you mind assigning it to me?

**Comment by daniknewgarden** [comment]
> Hi, im new to open source contributions but this issue seems perfect to get started. Would you mind assigning it to me?

Hey @lulek1410. I'm really happy that you want to support exo-ui. Of course, you can start with this issue. <br>
For now, we don't have everything documented, I want to create additional docs and wikis soon. So, feel free to ask me when you will need my help :smiley_cat:. <br>
Assigning the issue to you :+1:

**Comment by lulek1410** [comment]
i guess i can close this now right?

**Comment by daniknewgarden** [comment]
Added also some improvements in #35

**Comment by daniknewgarden** [comment]
Good job @lulek1410 :cat:. Thank you for your contribution!
